- true-business/yarn.lock
Added an empty components folder to src folder
- program runs normal after adding components folder
> add components folder in src folder, and .gitignore file

- true-business/package.json
- true-business/src/App.js
- true-business/src/components/NavBar.js
- true-business/src/css/LandingPage.css
- true-business/src/css/NavBar.css
- true-business/src/css/index.css
- true-business/src/index.js
- true-business/src/less/LandingPage.less
- true-business/src/less/NavBar.less
- true-business/src/less/index.less
Fixed the NavBar so that it hides the main component beneath when scrolling.
> Fixed NavBar Issue

- Procfile
Added a Procfile for heroku backend deployment.
- [XI have performed a self-review of my own code
- [XI My code has been reviewed by at least one peer
- [XI I have commented my code, particularly in hard-to-understand areas
- [XI I have made corresponding changes to the documentation
- [XI My changes generate no new warnings
- [XI I have added tests that prove my fix is effective or that my feature works
- [XI New and existing unit tests pass locally with my changes
> Added Procfile

- package.json
In attempt to satisfy the heroku gods and it's complaint about not finding command start, I tried adding a start script to the root level package.json.
> Added start script to Root Level Directory

- package.json
> Modified package.json for Heroku

- package.json
> Modifed package.json for heroku

- package.json
- yarn.lock
> modifed package.json/yarn.lock

- true-business/src/components/SignIn.js
- true-business/src/components/SignUp.js
- true-business/yarn.lock
I had made an PR with these same changes with a different branch, but realized it kept trying to mess up styling in NavBar.js so I created a new branch to make a new PR. Old PR closed.
> implement axios calls in SignIn.js and SignUp.js for users

- package.json
- true-business-backend/.gitignore
- true-business-backend/controllers/businessController.js
- true-business-backend/routes/index.js
- yarn.lock
> Passport Added googleauth backend

- true-business-backend/controllers/passportController.js
> changed naming convention to googleClientID

- true-business/package.json
- true-business/src/App.js
- true-business/src/components/Business.js
- true-business/src/css/Business.css
- true-business/src/less/Business.less
- true-business/yarn.lock
Also minor changes to Business layout.
> Changed package.json/build/yarn.lock

- true-business-backend/.gitignore
- true-business-backend/config/keys.js
- true-business-backend/controllers/passportController.js
Installing passport and changing the keys to uncrash the deployed backend made it so that local versions do not run. This PR added an OR statement to make it work locally and pushed the config file up to the repo. We'll have to change keys once we go live.
> Changes to stop local builds from crashing due to passport

- package.json
> Modified scripts in root package.json

- .vscode/settings.json
- package-lock.json
- true-business-backend/controllers/businessController.js
- true-business-backend/controllers/userController.js
- true-business-backend/models/user.js
- true-business-backend/package-lock.json
- true-business-backend/package.json
- true-business-backend/routes/index.js
Added the email validator in the register method.
Tested using postman.
> Business backend

- true-business/public/index.html
- true-business/src/App.js
- true-business/src/components/LandingPage.js
- true-business/src/components/NavBar.js
- true-business/src/components/SearchResults.js
- true-business/src/components/SignIn.js
- true-business/src/components/User.js
- true-business/src/css/App.css
- true-business/src/css/LandingPage.css
- true-business/src/css/SearchResults.css
- true-business/src/css/SignIn.css
- true-business/src/css/User.css
- true-business/src/css/index.css
- true-business/src/less/App.less
- true-business/src/less/LandingPage.less
- true-business/src/less/SearchResults.less
- true-business/src/less/SignIn.less
- true-business/src/less/User.less
- true-business/src/less/index.less
* Added User Component
* Modified styling for App/Landing/SearchResults/User/SignIn/Index as well slightly.
* Added a script to use Awesome Fonts on index.html.
It hasn't as it is mostly decorative.
> Added User Component

- true-business/package.json
- true-business/public/index.html
- true-business/src/components/NavBar.js
- true-business/src/components/NewReview.js
- true-business/src/components/SignIn.js
- true-business/src/components/User.js
- true-business/src/css/NewReview.css
- true-business/src/css/User.css
- true-business/src/less/NewReview.less
- true-business/src/less/User.less
- true-business/yarn.lock
* Added a NewReview Component.  At present it only works on the NavBar.  Still need to add it to the User Component.
* Also fixed the breadcrumbs on the User component, but I forgot to switch branches before pushing the NewReview stuff up.  Whoops...
> NewReview Component

- true-business-backend/controllers/userController.js
- true-business-backend/package-lock.json
- true-business-backend/package.json
I commented the email validator and removed the library until I'll figure it out. The library has a default Yarn installation and can't be removed.
> Removed Email Validator

- true-business/src/components/NavBar.js
- true-business/src/components/NewReview.js
- true-business/src/components/User.js
- true-business/src/css/NewReview.css
- true-business/src/less/NewReview.less
NewReview component now allows for image uploading.
Also adjust styling here and there.
- I tested it insofar as I uploaded an image and could see the preview of it and that the file for the image was on the state.  Until we decided how we are going to handle images, this is about as far as I could test it.
> Updated NewReview

- package.json
- yarn.lock
Added cookie-sessions to the root package.json
> Added cookie-sessions to the root package.json

- true-business/src/css/SignIn.css
- true-business/src/less/SignIn.less
Fixed hover on google login button
> Fixed hover on google login button

- true-business-backend/controllers/businessController.js
- true-business-backend/models/business.js
- true-business-backend/models/review.js
- true-business-backend/models/user.js
- true-business-backend/package.json
- true-business-backend/routes/index.js
- true-business-backend/server.js
- true-business-backend/yarn.lock
- true-business/src/App.js
- true-business/src/components/Business.js
- true-business/src/components/NavBar.js
- true-business/src/components/NewReview.js
- true-business/src/components/SearchResults.js
Started Stripe.  Hopefully if we all put our heads together we can figure this out today...
> Cody stripe

- package.json
- true-business/public/index.html
- true-business/src/components/SignUp.js
- true-business/src/components/StripePayment.js
- true-business/src/css/SignUp.css
- true-business/src/less/SignUp.less
- yarn.lock
Forgot to add the front end aspects of stripe to the last PR.  My bad.
> Stripe Bones

- true-business-backend/controllers/businessController.js
- true-business-backend/models/business.js
- true-business-backend/models/review.js
- true-business-backend/models/user.js
- true-business-backend/routes/index.js
- true-business-backend/server.js
- true-business/src/App.js
- true-business/src/components/Business.js
- true-business/src/components/NavBar.js
- true-business/src/components/NewReview.js
- true-business/src/components/SearchResults.js
* Added routes to search google, get details for a business, and create a business.  
* Modified the Navbar Component - removed the new review button (I believe this was the consensus to have it only on the business itself)
* Modified the Business Component- added a new review button that when clicked, adds a business, recieves the newly created business_id as a prop so it can be added to the database with the business reference.
_This might possibly break something, but to my knowledge, everything should be fine_
- I've repeatedly made new businesses.
> Google API for search/business addition to database

- package.json
- yarn.lock
> Added Stripe to Root

- true-business/src/App.js
- true-business/src/components/Business.js
- true-business/src/components/BusinessThumbnail.js
- true-business/src/components/LandingPage.js
- true-business/src/css/BusinessThumbnail.css
- true-business/src/css/GeneralStyles.css
- true-business/src/less/BusinessThumbnail.less
- true-business/src/less/GeneralStyles.less
delete dummy data on state in App.js  and can now directly get data from the database
We can now directly get businesses from the database. I deleted the dummy data on state in App.js.
We've not agreed on criteria on Featured Businesses and Popular Businesses, what we have right now is based on  boolean and number of stars, respectively.
> get businesses from database

- true-business/src/App.js
- true-business/src/components/Business.js
- true-business/src/components/LandingPage.js
Removed duplicate axios from App.js. I'm currently figuring out why route individual business is not working when you click on picture. Landingpage is working now
> remove duplicate axios and change props names in App.js

- true-business/src/App.js
> Added missing quote to business route

- true-business-backend/routes/index.js
Removed an import for something that didn't exist / was never referred to in the rest of the file.
> Fixed erroneous import

- true-business-backend/package.json
- true-business-backend/routes/authRoutes.js
- true-business-backend/services/passport.js
- true-business-backend/wala
- true-business-backend/yarn.lock
- true-business/package.json
- true-business/yarn.lock
> better dev v pro environment

- true-business-backend/controllers/userController.js
- true-business/src/components/NavBar.js
- true-business/src/components/SignIn.js
- true-business/src/components/User.js
currently using a place holder for hamburger
I added functionality to display hamburger when a user is logged in. A place holder is currently being used in place of hamburger until I appropriately wire components to do so.
> display hamburger when a user is logged in

- true-business-backend/controllers/userController.js
- true-business/package.json
- true-business/src/components/NavBar.js
- true-business/src/components/User.js
- true-business/yarn.lock
I installed @material-ui/core for menu and implemented user menu options. The reason why I put open 
menu instead of hamburger for now is because, like almost every website out there, hamburger menu should only be displayed when you're on a mobile or smaller device and not on a desktop.
> install  @material-ui/core for menu and implement user menu options

- true-business-backend/controllers/userController.js
- true-business-backend/routes/index.js
- true-business/src/components/NavBar.js
- true-business/src/components/SignIn.js
- true-business/src/components/User.js
I added updateUser route to the backend and change ID fields
> add updateUser route to backend and change ID fields

- true-business-backend/controllers/userController.js
- true-business-backend/models/user.js
- true-business/src/components/NavBar.js
- true-business/src/components/SignUp.js
- true-business/src/components/User.js
I added functionality to be able to change username and password. I made changes to database to enable it work. e.g, from findById to findOne and findByIdAndUpdate to findOneAndUpdate.
> Usersettings

- true-business/src/components/LandingPage.js
- true-business/src/components/NewReview.js
Splosion fix on Landingpage.js
> Fixed my splosion

- true-business-backend/models/review.js
- true-business/src/components/NewReview.js
Please include a summary of the change and a link to which issue is fixed. Please also include Made photos appear in review
> Made photos appear in review

- true-business/src/components/NewReview.js
Added dropzone image confirmed upload message.
> Added dropzone image confirmed upload message.

- true-business-backend/models/user.js
- true-business-backend/services/passport.js
Fixed a problem in the passport file which prevented the saving of a new user in the database.
Ran locally
> Fixed the user save in the passport file.

- package-lock.json
- true-business-backend/controllers/businessController.js
- true-business/src/App.js
- true-business/src/components/Business.js
- true-business/src/components/LandingPage.js
- true-business/src/components/NavBar.js
- true-business/src/components/NewReview.js
- true-business/src/components/SignIn.js
- true-business/src/components/SignUp.js
- true-business/src/components/StripePayment.js
- true-business/src/components/User.js
- true-business/src/css/Business.css
- true-business/src/css/Thumbnail.css
- true-business/src/less/Business.less
- true-business/src/less/Thumbnail.less
* Hoping this will solve our local / Heroku problem.
* Also fixed a bug in new businesses.
> Attempting Local & Heroku Deployment

- true-business-backend/controllers/reviewController.js
- true-business-backend/controllers/userController.js
- true-business-backend/models/business.js
- true-business-backend/models/review.js
- true-business-backend/models/user.js
- true-business/src/components/Business.js
- true-business/src/components/LandingPage.js
- true-business/src/components/NewReview.js
- true-business/src/components/SignUp.js
- true-business/src/css/Business.css
- true-business/src/css/NavBar.css
- true-business/src/less/Business.less
* Fixed User Registration (At least locally...)
* Gave users / reviews default images.  Still need to be styled. 
> User Registration / Default Photos

- true-business-backend/package.json
- true-business-backend/routes/index.js
- true-business-backend/yarn.lock
Added closing bracket to uncrash backend
> Added closing bracket to uncrash backend

- true-business-backend/controllers/userController.js
- true-business/src/components/SignIn.js
- true-business/src/components/SignUp.js
- true-business/src/components/User.js
- true-business/src/css/NavBar.css
- true-business/src/css/SearchResults.css
- true-business/src/css/SignIn.css
- true-business/src/css/SignUp.css
- true-business/src/css/Thumbnail.css
- true-business/src/less/SignIn.less
- true-business/src/less/SignUp.less
I implemented functionalities to handle and display Sign Up and Sign In errors on both front and back-end
> implement functionality to display Sign Up and Sign In errors on forms

- true-business-backend/controllers/reviewController.js
- true-business-backend/controllers/userController.js
- true-business/src/css/Business.css
- true-business/src/css/LandingPage.css
- true-business/src/css/Reviewer.css
- true-business/src/css/SearchResults.css
- true-business/src/css/Thumbnail.css
- true-business/src/css/User.css
- true-business/src/less/Thumbnail.less
- true-business/src/less/mixins.less
> Changed Styling / Heroku Logs

- true-business/src/components/SignIn.js
- true-business/src/components/SignUp.js
- true-business/src/css/Business.css
- true-business/src/css/LandingPage.css
- true-business/src/css/NavBar.css
- true-business/src/css/NewReview.css
- true-business/src/css/Reviewer.css
- true-business/src/css/SearchResults.css
- true-business/src/css/SignIn.css
- true-business/src/css/SignUp.css
- true-business/src/css/Stripe.css
- true-business/src/css/Thumbnail.css
- true-business/src/css/User.css
- true-business/src/less/mixins.less
> Fixed Styling, Removed Google

- true-business/src/css/Business.css
- true-business/src/css/LandingPage.css
- true-business/src/css/NavBar.css
- true-business/src/css/NewReview.css
- true-business/src/css/Reviewer.css
- true-business/src/css/SearchResults.css
- true-business/src/css/SignIn.css
- true-business/src/css/SignUp.css
- true-business/src/css/Stripe.css
- true-business/src/css/Thumbnail.css
- true-business/src/css/User.css
- true-business/src/less/Business.less
- true-business/src/less/LandingPage.less
- true-business/src/less/NavBar.less
- true-business/src/less/NewReview.less
- true-business/src/less/SearchResults.less
- true-business/src/less/SignIn.less
- true-business/src/less/SignUp.less
- true-business/src/less/User.less
- true-business/src/less/mixins.less
> Modified Styling

- true-business/src/css/Business.css
- true-business/src/css/LandingPage.css
- true-business/src/less/Business.less
- true-business/src/less/LandingPage.less
> Styling Updated
